version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

install:
#  - SET JAVA_HOME=C:\Program Files\Java\jdk1.7.0\bin
#  - SET PATH=%JAVA_HOME%;%PATH%
  - java -version
#  - echo %JDK_PATH%
  - echo %JAVA_HOME%
  - echo %PATH%

before_build:
- ps: >-
    nuget restore ForumDEG.sln

environment:
    project_name: 'ForumDEG'

# branches to build
branches:
  # whitelist
  only:
   - master
   - development

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# build Configuration, i.e. Debug, Release, etc.
configuration: Release
